[project]
name = "schorlarly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dacite>=1.9.2",
    "faiss-cpu>=1.13.2",
    "fastapi[all]>=0.128.0",
    "google-genai>=1.56.0",
    "numpy>=2.4.0",
    "openai>=2.14.0",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "requests>=2.32.5",
    "ruff>=0.14.10",
]

[dependency-groups]
dev = [
    "ty>=0.0.8",
]
